# Generated by Django 5.1.3 on 2025-01-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery3dHistory',
            fields=[
                ('index', models.IntegerField(blank=True, null=True)),
                ('issue', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('open_time', models.DateField()),
                ('front_winning_num', models.CharField(max_length=100)),
                ('back_winning_num', models.CharField(max_length=100)),
                ('seq_front_winning_num', models.CharField(max_length=100)),
                ('seq_back_winning_num', models.CharField(max_length=100)),
                ('sale_money', models.CharField(max_length=100)),
                ('r9_sale_money', models.CharField(max_length=100)),
                ('prize_pool_money', models.CharField(max_length=100)),
                ('week', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'lottery_3d',
            },
        ),
        migrations.CreateModel(
            name='LotteryKL8dHistory',
            fields=[
                ('index', models.IntegerField(blank=True, null=True)),
                ('issue', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('open_time', models.DateField()),
                ('front_winning_num', models.CharField(max_length=100)),
                ('back_winning_num', models.CharField(max_length=100)),
                ('seq_front_winning_num', models.CharField(max_length=100)),
                ('seq_back_winning_num', models.CharField(max_length=100)),
                ('sale_money', models.CharField(max_length=100)),
                ('r9_sale_money', models.CharField(max_length=100)),
                ('prize_pool_money', models.CharField(max_length=100)),
                ('week', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'lottery_kl8',
            },
        ),
        migrations.CreateModel(
            name='LotterySuperLottoHistory',
            fields=[
                ('index', models.IntegerField(blank=True, null=True, verbose_name='索引')),
                ('lottery_draw_num', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='期号')),
                ('draw_time', models.DateField(verbose_name='开奖日期')),
                ('front_area_result', models.CharField(max_length=20, verbose_name='前区开奖结果')),
                ('back_area_result', models.CharField(max_length=10, verbose_name='后区开奖结果')),
            ],
            options={
                'verbose_name': '超级大乐透历史记录',
                'verbose_name_plural': '超级大乐透历史记录',
                'db_table': 'lottery_super',
                'unique_together': {('index', 'lottery_draw_num')},
            },
        ),
    ]
